from datasets import load_dataset



# bug: Version have no attributes "match"

# load_dataset("visual_genome", "region_descriptions_v1.2.0", data_dir="data")
# load_dataset("visual_genome", "objects_v1.2.0", data_dir="data")
# load_dataset("visual_genome", "attributes_v1.2.0", data_dir="data")
# load_dataset("visual_genome", "relationships_v1.2.0", data_dir="data")
# load_dataset("visual_genome", "question_answers_v1.2.0", data_dir="data")






